[project]
name = "altair-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=5.5.0",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
    "polars>=1.34.0",
    "ruff>=0.13.1",
    "vega-datasets>=0.9.0",
]
